version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  postgres_data: